/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Contato;
import Classes.Mensagens;
import Conexao.util.salvarPerfil;
import Classes.Telefone;
import DAO.ContatoDAO;
import DAO.MensagensDAO;
import DAO.TelefoneDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class CadastroMensagem extends javax.swing.JFrame {

    private ArrayList contatos = new ArrayList();
    private int meuFone = 0;

    /**
     * Creates new form CadastroMensagem
     */
    public CadastroMensagem() {
        initComponents();
        if (salvarPerfil.le() == null) {
            JOptionPane.showMessageDialog(this,
                    "Você precisa entrar em um perfil antes de conversar.\n"
                    + "(Controle > Perfil > Entrar > Entrar em Existente)");
            return;
        }
        lblDe.setText("De: " + salvarPerfil.le().getNome());
        Telefone meu = new TelefoneDAO().procurarPorPessoa(salvarPerfil.le().getID_pessoa());
        meuFone = meu.getID_fone();
        if (meuFone == 0) {
            JOptionPane.showMessageDialog(this,
                    "Seu perfil não tem telefone cadastrado, então não dá para enviar mensagens.");
        }
        carregarContatos();
    }

    private void carregarContatos() {
        contatos = new ContatoDAO().listarPorPessoa(salvarPerfil.le().getID_pessoa());
        javax.swing.DefaultComboBoxModel<String> model = new javax.swing.DefaultComboBoxModel<>();
        for (Object o : contatos) {
            Contato c = (Contato) o;
            model.addElement(c.getNomeContato() + " (" + c.getFoneContato() + ")");
        }
        comboContato.setModel(model);
        mostrarConversa();
    }

    private void mostrarConversa() {
        areaConversa.setText("");
        Contato c = getContatoSelecionado();
        if (c == null || meuFone == 0) {
            return;
        }
        ArrayList msgs = new MensagensDAO().listarConversa(meuFone, c.getId_telefone());
        for (Object o : msgs) {
            Mensagens m = (Mensagens) o;
            String quem = (m.getID_remetente() == meuFone) ? "Eu" : c.getNomeContato();
            areaConversa.append(quem + ": " + m.getMensagem() + "\n");
        }
    }

    private Contato getContatoSelecionado() {
        int i = comboContato.getSelectedIndex();
        if (i < 0 || i >= contatos.size()) {
            return null;
        }
        return (Contato) contatos.get(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDe = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboContato = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaConversa = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtMensagem = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conversas Pessoais");

        lblDe.setText("De:");

        jLabel1.setText("Para (contato):");

        comboContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboContatoActionPerformed(evt);
            }
        });

        areaConversa.setEditable(false);
        areaConversa.setColumns(20);
        areaConversa.setRows(5);
        jScrollPane1.setViewportView(areaConversa);

        jLabel2.setText("Mensagem:");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                    .addComponent(lblDe)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMensagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDe)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboContatoActionPerformed
        mostrarConversa();
    }//GEN-LAST:event_comboContatoActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        if (salvarPerfil.le() == null || meuFone == 0) {
            JOptionPane.showMessageDialog(this, "Você precisa de um perfil com telefone para enviar.");
            return;
        }
        Contato c = getContatoSelecionado();
        if (c == null) {
            JOptionPane.showMessageDialog(this, "Escolha um contato para conversar.");
            return;
        }
        if (txtMensagem.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite uma mensagem.");
            return;
        }
        try {
            Mensagens mensagem = new Mensagens();
            mensagem.setMensagem(txtMensagem.getText());
            mensagem.setID_remetente(meuFone);
            mensagem.setID_destinatario(c.getId_telefone());

            new MensagensDAO().inserir(mensagem);
            txtMensagem.setText("");
            mostrarConversa();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao enviar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaConversa;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JComboBox<String> comboContato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDe;
    private javax.swing.JTextField txtMensagem;
    // End of variables declaration//GEN-END:variables
}
