/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Contato;
import Conexao.util.salvarPerfil;
import Classes.Telefone;
import DAO.ContatoDAO;
import DAO.TelefoneDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class CadastroContato extends javax.swing.JFrame {

    private ArrayList contatos = new ArrayList();

    /**
     * Creates new form CadastroContato
     */
    public CadastroContato() {
        initComponents();
        if (salvarPerfil.le() == null) {
            JOptionPane.showMessageDialog(this,
                    "Você precisa entrar em um perfil antes de mexer nos contatos.\n");
        } else {
            lblUsuario.setText("Contatos de: " + salvarPerfil.le().getNome());
            carregarContatos();
        }
    }

    private void carregarContatos() {
        if (salvarPerfil.le() == null) {
            return;
        }
        ContatoDAO dao = new ContatoDAO();
        contatos = dao.listarPorPessoa(salvarPerfil.le().getID_pessoa());
        javax.swing.DefaultListModel<String> model = new javax.swing.DefaultListModel<>();
        for (Object o : contatos) {
            Contato c = (Contato) o;
            model.addElement(c.getNomeContato() + " (" + c.getFoneContato() + ")");
        }
        listaContatos.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDDD = new javax.swing.JTextField();
        txtFone = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaContatos = new javax.swing.JList<>();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contatos");

        lblUsuario.setText("Contatos");

        jLabel1.setText("Adicionar (DDI + número):");

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listaContatos);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtDDD, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFone, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        if (salvarPerfil.le() == null) {
            JOptionPane.showMessageDialog(this, "Entre em um perfil primeiro.");
            return;
        }
        String ddd = txtDDD.getText().trim();
        String numero = txtFone.getText().trim();
        if (ddd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o DDI.");
            return;
        }
        if (numero.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um número de telefone.");
            return;
        }
        int dddNumero;
        try {
            dddNumero = Integer.parseInt(ddd);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "DDI deve ser um número (ex.: 11).");
            return;
        }
        try {
            TelefoneDAO telefoneDAO = new TelefoneDAO();
            Telefone telefone = telefoneDAO.procurarPorNumero(numero, dddNumero);

            if (telefone.getID_fone() == 0) {
                JOptionPane.showMessageDialog(this, "Esse número não está cadastrado");
                return;
            }
            if (telefone.getID_pessoa() == salvarPerfil.le().getID_pessoa()) {
                JOptionPane.showMessageDialog(this, "Você não pode adicionar o seu próprio número.");
                return;
            }

            ContatoDAO contatoDAO = new ContatoDAO();
            if (contatoDAO.existe(salvarPerfil.le().getID_pessoa(), telefone.getID_fone())) {
                JOptionPane.showMessageDialog(this, "Esse contato já está na sua lista");
                return;
            }

            Contato contato = new Contato();
            contato.setId_pessoa(salvarPerfil.le().getID_pessoa());
            contato.setId_telefone(telefone.getID_fone());
            contatoDAO.inserir(contato);

            Telefone meuTelefone = telefoneDAO.procurarPorPessoa(salvarPerfil.le().getID_pessoa());
            if (meuTelefone.getID_fone() == 0) {
                JOptionPane.showMessageDialog(this,
                        "Contato adicionado só para você. Como você não tem telefone cadastrado, "
                        + "a outra pessoa não pôde te adicionar de volta.");
            } else {
                if (!contatoDAO.existe(telefone.getID_pessoa(), meuTelefone.getID_fone())) {
                    Contato contatoVolta = new Contato();
                    contatoVolta.setId_pessoa(telefone.getID_pessoa());
                    contatoVolta.setId_telefone(meuTelefone.getID_fone());
                    contatoDAO.inserir(contatoVolta);
                }
                JOptionPane.showMessageDialog(this, "Contato adicionado nos dois lados!");
            }

            txtDDD.setText("");
            txtFone.setText("");
            carregarContatos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar contato: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Contato c = getSelecionado();
        if (c == null) {
            return;
        }
        String novoDDD = JOptionPane.showInputDialog(this, "Novo DDI:");
        if (novoDDD == null || novoDDD.trim().isEmpty()) {
            return;
        }
        String novoNumero = JOptionPane.showInputDialog(this, "Novo número:");
        if (novoNumero == null || novoNumero.trim().isEmpty()) {
            return;
        }
        int dddNumero;
        try {
            dddNumero = Integer.parseInt(novoDDD.trim());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "DDI deve ser um número (ex.: 11).");
            return;
        }
        try {
            Telefone telefone = new TelefoneDAO().procurarPorNumero(novoNumero.trim(), dddNumero);
            if (telefone.getID_fone() == 0) {
                JOptionPane.showMessageDialog(this, "Esse número não está cadastrado no app.");
                return;
            }
            if (telefone.getID_pessoa() == salvarPerfil.le().getID_pessoa()) {
                JOptionPane.showMessageDialog(this, "Você não pode usar o seu próprio número.");
                return;
            }
            c.setId_telefone(telefone.getID_fone());
            new ContatoDAO().atualizar(c);
            JOptionPane.showMessageDialog(this, "Contato atualizado!");
            carregarContatos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao editar contato: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Contato c = getSelecionado();
        if (c == null) {
            return;
        }
        int resposta = JOptionPane.showConfirmDialog(this,
                "Excluir o contato \"" + c.getNomeContato() + "\"?",
                "Confirmar exclusão", JOptionPane.YES_NO_OPTION);
        if (resposta != JOptionPane.YES_OPTION) {
            return;
        }
        new ContatoDAO().excluir(c.getId_contato());
        JOptionPane.showMessageDialog(this, "Contato excluído!");
        carregarContatos();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private Contato getSelecionado() {
        int i = listaContatos.getSelectedIndex();
        if (i < 0 || i >= contatos.size()) {
            JOptionPane.showMessageDialog(this, "Selecione um contato na lista.");
            return null;
        }
        return (Contato) contatos.get(i);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JList<String> listaContatos;
    private javax.swing.JTextField txtDDD;
    private javax.swing.JTextField txtFone;
    // End of variables declaration//GEN-END:variables
}
