/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Pessoa;
import Conexao.util.salvarPerfil;
import DAO.PessoaDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class Entrar extends javax.swing.JFrame {

    private ArrayList listaPessoas = new ArrayList();

    /**
     * Creates new form Entrar
     */
    public Entrar() {
        initComponents();
        carregarPessoas();
    }

    private void carregarPessoas() {
        try {
            PessoaDAO dao = new PessoaDAO();
            listaPessoas = dao.listar();
            javax.swing.DefaultComboBoxModel<String> model = new javax.swing.DefaultComboBoxModel<>();
            for (Object o : listaPessoas) {
                Pessoa p = (Pessoa) o;
                model.addElement(p.getID_pessoa() + " - " + p.getNome());
            }
            ComboEntrar.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar perfis: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        ComboEntrar = new javax.swing.JComboBox<>();
        BLSair = new javax.swing.JButton();
        BEntrar1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ComboEntrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BLSair.setText("Sair");
        BLSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLSairActionPerformed(evt);
            }
        });

        BEntrar1.setText("Entrar");
        BEntrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEntrar1ActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(BLSair, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BEntrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ComboEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BEntrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BLSair, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BLSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLSairActionPerformed
        dispose();
    }//GEN-LAST:event_BLSairActionPerformed

    private void BEntrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEntrar1ActionPerformed
        int i = ComboEntrar.getSelectedIndex();
        if (i < 0 || listaPessoas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum perfil selecionado.");
            return;
        }
        Pessoa p = (Pessoa) listaPessoas.get(i);
        salvarPerfil.grava(p.getID_pessoa());
        JOptionPane.showMessageDialog(this, "Bem-vindo(a), " + p.getNome() + "!");
        dispose();
    }//GEN-LAST:event_BEntrar1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BEntrar1;
    private javax.swing.JButton BLSair;
    private javax.swing.JComboBox<String> ComboEntrar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
