/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Configuracao;
import Classes.Pessoa;
import Conexao.util.salvarPerfil;
import DAO.PessoaDAO;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {


    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnCriar = new javax.swing.JButton();
        btnContatos = new javax.swing.JButton();
        btnConversas = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();
        MenuBar1 = new javax.swing.JMenuBar();
        controle = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        MEntrar = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        EditarPessoa = new javax.swing.JMenuItem();
        ExcluirPessoa = new javax.swing.JMenuItem();
        Contato = new javax.swing.JMenu();
        InserirCont = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        CPessoais = new javax.swing.JMenuItem();
        listarPerfis = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Bem Vindo!!!!");

        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCriar.setText("Criar Perfil");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        btnContatos.setText("Contatos");
        btnContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContatosActionPerformed(evt);
            }
        });

        btnConversas.setText("Conversas");
        btnConversas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConversasActionPerformed(evt);
            }
        });

        btnConfig.setText("Configurações");
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });

        controle.setText("Controle");

        jMenu1.setText("Perfil");

        MEntrar.setText("Entrar");

        jMenuItem2.setText("Entrar em Existente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MEntrar.add(jMenuItem2);

        jMenuItem3.setText("Criar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MEntrar.add(jMenuItem3);

        jMenu1.add(MEntrar);

        EditarPessoa.setText("Editar");
        EditarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(EditarPessoa);

        ExcluirPessoa.setText("Excluir");
        ExcluirPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(ExcluirPessoa);

        controle.add(jMenu1);

        Contato.setText("Contato");

        InserirCont.setText("Editar");
        InserirCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirContActionPerformed(evt);
            }
        });
        Contato.add(InserirCont);

        controle.add(Contato);

        MenuBar1.add(controle);

        jMenu4.setText("Conversas");

        CPessoais.setText("Pessoais");
        CPessoais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPessoaisActionPerformed(evt);
            }
        });
        jMenu4.add(CPessoais);

        listarPerfis.setText("Listar todos perfis");
        listarPerfis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPerfisActionPerformed(evt);
            }
        });
        jMenu4.add(listarPerfis);

        MenuBar1.add(jMenu4);

        jMenu6.setText("Ferramentas");

        jMenuItem5.setText("Configurações");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        MenuBar1.add(jMenu6);

        setJMenuBar(MenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConversas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConversas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JFrame Conf = new Configuracoes();
        Conf.setLocationRelativeTo(rootPane);
        Conf.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void InserirContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirContActionPerformed
        abrirContatos();
    }//GEN-LAST:event_InserirContActionPerformed

    private void abrirContatos() {
        if (salvarPerfil.le() == null) {
            JOptionPane.showMessageDialog(rootPane, "Entre em um perfil primeiro (Perfil > Entrar).");
            return;
        }
        JFrame tela = new CadastroContato();
        tela.setLocationRelativeTo(rootPane);
        tela.setVisible(true);
    }

    private void CPessoaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPessoaisActionPerformed
        JFrame tela = new CadastroMensagem();
        tela.setLocationRelativeTo(rootPane);
        tela.setVisible(true);
    }//GEN-LAST:event_CPessoaisActionPerformed

    private void listarPerfisActionPerformed(java.awt.event.ActionEvent evt) {
        JFrame tela = new ListarPerfis();
        tela.setLocationRelativeTo(rootPane);
        tela.setVisible(true);
    }

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFrame Login = new Entrar();
        Login.setLocationRelativeTo(rootPane);
        Login.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JFrame tela = new CadastroPessoa();
        tela.setLocationRelativeTo(rootPane);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void EditarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarPessoaActionPerformed
        if (salvarPerfil.le() == null) {
            JOptionPane.showMessageDialog(rootPane, "Entre em um perfil primeiro (Perfil > Entrar).");
            return;
        }
        JFrame tela = new EditarPerfil();
        tela.setLocationRelativeTo(rootPane);
        tela.setVisible(true);
    }//GEN-LAST:event_EditarPessoaActionPerformed

    private void ExcluirPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirPessoaActionPerformed
        if (salvarPerfil.le() == null) {
            JOptionPane.showMessageDialog(rootPane, "Entre em um perfil primeiro (Perfil > Entrar).");
            return;
        }
        int resposta = JOptionPane.showConfirmDialog(rootPane,
                "Tem certeza que deseja excluir o perfil \"" + salvarPerfil.le().getNome() + "\"?\n"
                + "Isso também apaga os telefones e contatos ligados a ele.",
                "Confirmar exclusão", JOptionPane.YES_NO_OPTION);

        if (resposta != JOptionPane.YES_OPTION) {
            return;
        }

        int id = salvarPerfil.le().getID_pessoa();
        try {
            // O banco tem ON DELETE CASCADE, então apagar a pessoa já remove
            // telefones, contatos e mensagens ligados a ela.
            new PessoaDAO().excluir(id);

            // Confere se a pessoa realmente saiu do banco (o DAO não relança erros).
            Pessoa ainda = new PessoaDAO().procurar(id);
            if (ainda == null || ainda.getID_pessoa() == 0) {
                salvarPerfil.apaga();
                JOptionPane.showMessageDialog(rootPane, "Perfil excluído com sucesso!");
            } else {
                JOptionPane.showMessageDialog(rootPane,
                        "Não foi possível excluir o perfil. Verifique o console para detalhes.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao excluir o perfil: " + e.getMessage());
        }
    }//GEN-LAST:event_ExcluirPessoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame Login = new Entrar();
        Login.setLocationRelativeTo(rootPane);
        Login.setVisible(true);    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        JFrame tela = new CadastroPessoa();
        tela.setLocationRelativeTo(rootPane);
        tela.setVisible(true);
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContatosActionPerformed
        abrirContatos();
    }//GEN-LAST:event_btnContatosActionPerformed

    private void btnConversasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConversasActionPerformed
        if (salvarPerfil.le() == null) {
            JOptionPane.showMessageDialog(rootPane, "Entre em um perfil primeiro (botão Entrar).");
            return;
        }
        JFrame tela = new CadastroMensagem();
        tela.setLocationRelativeTo(rootPane);
        tela.setVisible(true);
    }//GEN-LAST:event_btnConversasActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        JFrame tela = new Configuracoes();
        tela.setLocationRelativeTo(rootPane);
        tela.setVisible(true);
    }//GEN-LAST:event_btnConfigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Principal().setVisible(true);
                JFrame Janela = new Principal();
                Janela.setVisible(true);
                Janela.setLocationRelativeTo(null); //Centraliza a Janela
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CPessoais;
    private javax.swing.JMenu Contato;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnContatos;
    private javax.swing.JButton btnConversas;
    private javax.swing.JButton btnCriar;
    private javax.swing.JMenuItem EditarPessoa;
    private javax.swing.JMenuItem ExcluirPessoa;
    private javax.swing.JMenuItem InserirCont;
    private javax.swing.JMenu MEntrar;
    private javax.swing.JMenuBar MenuBar1;
    private javax.swing.JMenu controle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem listarPerfis;
    // End of variables declaration//GEN-END:variables

}
